#!/bin/bash

set -euo pipefail

findDifferences() {
    path1=$1
    path2=$2

    echo "Files not found in $path2:"
    filesNotFoundInPath2=()
    
    while read -r filePath
    do

    fileName="${filePath##*/}"
    if [[ ${fileName:0:1} != '.' ]]; then
        relativePath="${filePath##*$path1/}"
        filePath2="$path2/$relativePath"

        if [[ ! -e $filePath2 ]]; then
            filesNotFoundInPath2+=("$filePath")
            echo "$filePath"
        fi
    fi

    done < <(find $path1 -type f)

    echo
    echo "-----------------"
    echo

    echo "Files not found in $path1:"
    filesNotFoundInPath1=()
    
    while read -r filePath
    do

    fileName="${filePath##*/}"
    if [[ ${fileName:0:1} != '.' ]]; then
        relativePath="${filePath##*$path2/}"
        filePath1="$path1/$relativePath"

        if [[ ! -e $filePath1 ]]; then
            filesNotFoundInPath1+=("$filePath")
            echo "$filePath"
        fi
    fi

    done < <(find $path2 -type f)
}

if [ $# -ne 2 ] ; then
    echo "Usage: $0 path1 path2" >&2
    exit 1
fi

findDifferences $1 $2