#!/bin/bash

set -euo pipefail

copyFilesToPath() {
    local originParentDir=$1
    local targetParentDir=$2
    shift
    shift
    local originfilePaths=("$@")

    for originFilePath in "${originfilePaths[@]}"; do
        local relativeFilePath="${originFilePath##*$originParentDir/}"
        local targetFilePath="$targetParentDir/$relativeFilePath"
        local targetFileDir="${targetFilePath%/*}"

        mkdir -p "$targetFileDir"
        cp "$originFilePath" "$targetFilePath"
    done
}

sync() {
    parentDir1=$1
    parentDir2=$2

    echo "Files not found in $parentDir2:"
    local filesNotFoundInPath2=()
    
    while read -r filePath
    do

    local fileName="${filePath##*/}"
    if [[ ${fileName:0:1} != '.' ]]; then
        local relativePath="${filePath##*$parentDir1/}"
        local filePath2="$parentDir2/$relativePath"

        if [[ ! -e $filePath2 ]]; then
            filesNotFoundInPath2+=("$filePath")
            echo "$filePath"
        fi
    fi

    done < <(find "$parentDir1" -type f)

    if [[ ${#filesNotFoundInPath2[@]} -ne 0 ]]
    then
        copyFilesToPath "$parentDir1" "$parentDir2" "${filesNotFoundInPath2[@]}"
    else
        echo "$parentDir2 has all the files in $parentDir1."
    fi

    echo
    echo "-----------------"
    echo

    echo "Files not found in $parentDir1:"
    local filesNotFoundInPath1=()
    
    while read -r filePath
    do

    local fileName="${filePath##*/}"
    if [[ ${fileName:0:1} != '.' ]]; then
        local relativePath="${filePath##*$parentDir2/}"
        local filePath1="$parentDir1/$relativePath"

        if [[ ! -e $filePath1 ]]; then
            filesNotFoundInPath1+=("$filePath")
            echo "$filePath"
        fi
    fi

    done < <(find "$parentDir2" -type f)

    if [[ ${#filesNotFoundInPath1[@]} -ne 0 ]]
    then
        copyFilesToPath "$parentDir2" "$parentDir1" "${filesNotFoundInPath1[@]}"
    else
        echo "$parentDir1 has all the files in $parentDir2."
    fi

    echo
    echo "------------"
    echo "SYNCHRONIZED"
    echo "------------"
}

if [ $# -ne 2 ] ; then
    echo "Usage: $0 parentDir1 parentDir2" >&2
    exit 1
fi

sync $1 $2